import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../../context/provider";
import { ApolloWrapper } from "./ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html className="h-full bg-white">
      <Provider>
        <body className={`${inter.className} h-full`}>
          <ApolloWrapper>{children}</ApolloWrapper>
        </body>
      </Provider>
    </html>
  );
}
